version: '3.2'
services:

  base:
    build: imgs/base

  test:
    image: vonmo-rocker-rocker-base:latest
    depends_on:
      - base
    volumes:
      - "./:/project:Z"
    tmpfs:
      - /run
      - /tmp
